Repository eleven-labs/codelabs, pull requests merged in 2018-03, with the labels that each got.

#49 Edit flask icon
  src/assets/images/icons/icon_flask.png
  src/assets/images/icons/icon_flask.svg
  src/assets/scss/objects/_splash.scss
  src/components/Splash.jsx
Labels: fix, mergeable

#50 Edit welcome text
  src/assets/scss/objects/_splash.scss
  src/components/Splash.jsx
Labels: fix, mergeable

#52 Course reading time
  _posts/codelabs/index.json
  createjson.js
  src/components/CourseItem.jsx
  src/containers/Course.jsx
Labels: feat, mergeable

#53 Add Eleven Codelabs logo
  src/assets/images/logo_eleven_codelabs.png
  src/assets/scss/includes/_header.scss
  src/containers/Header.jsx
Labels: feat, mergeable

#51 Adjust overall presentation
  src/assets/images/icons/icon_english.svg
  src/assets/images/icons/icon_rocket.svg
  src/assets/scss/base/_global.scss
  src/assets/scss/includes/_header.scss
  src/assets/scss/objects/_course-page.scss
  src/assets/scss/objects/_layout.scss
  src/containers/Course.jsx
  src/containers/Header.jsx
Labels: fix

#59 feat: add graphql tuto
  _posts/assets/2017-09-11-mon-premier-tuto/cover.jpg
  _posts/assets/2017-09-11-mon-premier-tuto/step1.jpg
  _posts/assets/2017-09-11-mon-premier-tuto/step2.jpg
  _posts/assets/2018-03-20-graphql-avec-apollo/cover.png
  _posts/assets/2018-03-20-graphql-avec-apollo/documentation.png
  _posts/assets/2018-03-20-graphql-avec-apollo/hello.png
  _posts/assets/2018-03-20-graphql-avec-symfony/cover.png
  _posts/assets/2018-03-20-graphql-avec-symfony/symfony.png
  _posts/codelabs/2018-03-20-graphql-avec-apollo/index.json
  _posts/codelabs/2018-03-20-graphql-avec-apollo/index.md
  _posts/codelabs/2018-03-20-graphql-avec-apollo/step1.md
  _posts/codelabs/2018-03-20-graphql-avec-apollo/step2.md
  _posts/codelabs/2018-03-20-graphql-avec-apollo/step3.md
  _posts/codelabs/2018-03-20-graphql-avec-apollo/step4.md
  _posts/codelabs/2018-03-20-graphql-avec-apollo/step5.md
  _posts/codelabs/2018-03-20-graphql-avec-symfony/index.json
  _posts/codelabs/2018-03-20-graphql-avec-symfony/index.md
  _posts/codelabs/2018-03-20-graphql-avec-symfony/step1.md
  _posts/codelabs/2018-03-20-graphql-avec-symfony/step2.md
  _posts/codelabs/2018-03-20-graphql-avec-symfony/step3.md
  _posts/codelabs/2018-03-20-graphql-avec-symfony/step4.md
  _posts/codelabs/2018-03-20-graphql-avec-symfony/step5.md
  createjson.js
Labels: RFR, publication

#55 Add new tutorial: API versioning et rétro-compatibilité avec Symfony
  _posts/codelabs/2018-03-04-api-versioning-et-retro-compatibilite-avec-symfony/index.json
  _posts/codelabs/2018-03-04-api-versioning-et-retro-compatibilite-avec-symfony/index.md
  _posts/codelabs/2018-03-04-api-versioning-et-retro-compatibilite-avec-symfony/step1.md
  _posts/codelabs/2018-03-04-api-versioning-et-retro-compatibilite-avec-symfony/step2.md
  _posts/codelabs/2018-03-04-api-versioning-et-retro-compatibilite-avec-symfony/step3.md
  _posts/codelabs/2018-03-04-api-versioning-et-retro-compatibilite-avec-symfony/step4.md
  _posts/codelabs/2018-03-04-api-versioning-et-retro-compatibilite-avec-symfony/step5.md
Labels: RFR

#88 Added a schema on API versioning tutorial
  _posts/assets/2018-03-28-api-versioning-et-retrocompatibilite-avec-symfony/schema.jpg
  _posts/codelabs/2018-03-28-api-versioning-et-retrocompatibilite-avec-symfony/index.md
Labels: RFR
