Repository eleven-labs/codelabs, pull requests merged in 2018-05, with the labels that each got.

#112 add tuto microservice-avec-go-et-grpc
  _posts/codelabs/2018-05-15-microservice-avec-go-et-grpc/index.json
  _posts/codelabs/2018-05-15-microservice-avec-go-et-grpc/index.md
  _posts/codelabs/2018-05-15-microservice-avec-go-et-grpc/step1.md
  _posts/codelabs/2018-05-15-microservice-avec-go-et-grpc/step2.md
  _posts/codelabs/2018-05-15-microservice-avec-go-et-grpc/step3.md
  _posts/codelabs/2018-05-15-microservice-avec-go-et-grpc/step4.md
  _posts/codelabs/2018-05-15-microservice-avec-go-et-grpc/step5.md
  _posts/codelabs/2018-05-15-microservice-avec-go-et-grpc/step6.md
Labels: RFR, publication

#117 style(summary step): add transition to step number background color
  src/assets/scss/objects/_course-page.scss
Labels: RFR, feat

#94 add react helmet to update page title and meta tags
  package.json
  src/constants.js
  src/containers/Course.jsx
  src/helpers/course.js
  src/index.ejs
  yarn.lock
Labels: done, feat

#113 Add link to course play icon
  src/assets/scss/objects/_course-item.scss
  src/components/CourseItem.jsx
Labels: done, feat

#118 Add uppercase in title
  _posts/codelabs/2018-05-15-microservice-avec-go-et-grpc/index.json
Labels: RFR, fix
