Repository eleven-labs/codelabs, pull requests merged in 2019-05, with the labels that each got.

#133 fix language declaration and node version in travis, and add supported version in circleci
  .circleci/config.yml
  .travis.yml
Labels: RFR, fix

#131 Add new tutorial on apollo / rest & cache
  _posts/assets/2019-05-10-apollo-rest-cache/authentication_key.png
  _posts/assets/2019-05-10-apollo-rest-cache/cache-schema.png
  _posts/assets/2019-05-10-apollo-rest-cache/graphql.png
  _posts/assets/2019-05-10-apollo-rest-cache/persisted_queries.png
  _posts/assets/2019-05-10-apollo-rest-cache/persisted_queries_result.png
  _posts/assets/2019-05-10-apollo-rest-cache/redis_cache.png
  _posts/assets/2019-05-10-apollo-rest-cache/result1.png
  _posts/assets/2019-05-10-apollo-rest-cache/result2.png
  _posts/codelabs/2019-05-10-apollo-rest-cache/index.json
  _posts/codelabs/2019-05-10-apollo-rest-cache/index.md
  _posts/codelabs/2019-05-10-apollo-rest-cache/step1.md
  _posts/codelabs/2019-05-10-apollo-rest-cache/step2.md
  _posts/codelabs/2019-05-10-apollo-rest-cache/step3.md
Labels: publication

#134 Fix reply issue
  _posts/codelabs/2019-05-10-apollo-rest-cache/index.json
Labels: fix

#135 Fix slug and update README
  README.md
  _posts/codelabs/2019-05-10-apollo-rest-cache/index.json
Labels: RFR, fix
